services:
  fragrance-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9876:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
