services:
  fragrance-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Dışarıdan 9000, içeriden 9000 portu
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
